#!/usr/bin/env bash
# Sync content/spec and content/skills from their source repos and open a PR.
# The sources are canonical; the copies in content/ are generated. Uses your gh login.
set -euo pipefail
cd "$(dirname "$0")/.."
git fetch -q origin main
BRANCH="content/sync-$(date +%Y%m%d-%H%M)"
git switch -q -c "$BRANCH" origin/main
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
for d in spec skills; do
  gh repo clone "devrel-md/$d" "$TMP/$d" -- -q --depth 1
  sha=$(git -C "$TMP/$d" rev-parse HEAD); if [ "$d" = spec ]; then SPEC_SHA=$sha; else SKILLS_SHA=$sha; fi
  find "content/$d" -mindepth 1 ! -name SYNCED-FROM.md -delete
  rsync -a --exclude .git --exclude .gitignore "$TMP/$d/" "content/$d/"
done
printf '{\n  "spec": {"repo": "devrel-md/spec", "commit": "%s"},\n  "skills": {"repo": "devrel-md/skills", "commit": "%s"}\n}\n' "$SPEC_SHA" "$SKILLS_SHA" > content/SOURCES.json
if git diff --quiet && git diff --cached --quiet && [ -z "$(git status --porcelain)" ]; then
  echo "Content already up to date."; git switch -q -; git branch -q -D "$BRANCH"; exit 0
fi
git add -A content
git commit -qm "Sync spec and skills content (spec ${SPEC_SHA:0:7}, skills ${SKILLS_SHA:0:7})"
git push -q -u origin "$BRANCH"
gh pr create --base main --head "$BRANCH" --title "Sync spec and skills content" \
  --body "Generated by scripts/sync-content.sh. Sources: devrel-md/spec@${SPEC_SHA:0:7}, devrel-md/skills@${SKILLS_SHA:0:7}. Review the preview before merging."
